# Generated by Django 4.2.16 on 2024-10-16 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='text_news',
            field=models.TextField(default=1),
        ),
    ]
