# Generated by Django 4.2.16 on 2024-10-16 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0002_news_text_news'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='text_news',
            field=models.TextField(),
        ),
    ]
