# Generated by Django 4.2.16 on 2024-10-23 11:49

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('simpleapp', '0003_alter_news_text_news'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='datetime_news',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
